version: '3.8'

services:
  laravel-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
      - node-notify
    volumes:
      - ./backend:/var/www/html

  node-notify:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    container_name: node-notify
    ports:
      - "3001:3001"
    env_file:
      - ./backend/notification-service/.env
    volumes:
      - ./backend/notification-service:/app

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: sahmfood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
